#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#cp -r ../Marylebone_mesh/constant/polyMesh constant/polyMesh/.

decomposePar
mpirun -np 8 pisoFoamTurbulentScalarTransport -parallel

#------------------------------------------------------------------------------
